version: '2.29.7'
services:
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app-timesheet:
    depends_on:
      - db-mysql
    image: rihemtaieb/tp-foyer:1.0.0
    ports:
      - 8082:8082

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db-mysql:3306/db?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"

      }'
      stdin_open: true
      tty: true

volumes:
  db: