version: "2.29.7"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-tpfoyer:
    depends_on:
      - mysqldb
    image: hachichamohamed/tp-foyer:5.2.0
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "management.endpoints.web.exposure.include" : "*",
        "management.endpoint.prometheus.enabled" : "true",
        "management.endpoints.web.base-path" : "/actuator"
      }'
    stdin_open: true
    tty: true

volumes:
  db :
